### ISSUE TITLE
jira_dbconnector: postgresql

### ISSUE THREAD

**Issue by felipe1982** [phips/ansible-jira#1]
I don't see where this value is being used `jira_dbconnector: postgresql`

Also, where do I set DB hostname, username, password for remote connection to DB?

**Comment by phips** [comment]
Hello @felipe1982 – oof, this is a bit old now, and probably a load of rubbish! It looks like jira_dbconnector isn't used anywhere, so you're correct to spot that. From what I recall, the database information is prompted for – in the web UI – when you first start up Jira. If you find things to fix in this role please do issue a PR and I'll happily pull them back in. Thanks!
